#!/bin/sh

# Set this to the password to your secret keyring
PGPPASS=mypassword
# Set this to the directory you keep your PGP keyrings and config files at
PGPPATH=/usr6/rob/.pgp
# Set this to your user name, the name on your secret key
PGPUSER=robm@ncsa.uiuc.edu
# Set this to the full pathname of the PGP binary on your system
PGPBIN=/usr/local/bin/pgp

# That should be all you need to edit

export PGPPASS
export PGPPATH

# Make sure PGP doesn't try to make temp files in /
cd /tmp

exec $PGPBIN -fe $* -u $PGPUSER 2>/dev/null
