#!/bin/sh

# Set this to wherever you placed my hacked version of uudecode
HACKED_UUDECODE=/X11/robm/Mosaic/auth/uudecode
# Set this to the name of your key, or your user name.
PEMUSER=robm@ncsa.uiuc.edu
# Set these to the location of your public and secret key files
PUBKEY=$HOME/.key-public
SECKEY=$HOME/.key-secret
# Set this to the password to your secret key
KEYPASS=mypassword
# Set this to the location of your RIPEM executable
RIPEMBIN=/usr/local/bin/ripem

# That should be all you need to edit

$RIPEMBIN -d -Y g -u $PEMUSER -p $PUBKEY -s $SECKEY -k $KEYPASS | $HACKED_UUDECODE
