#!/bin/sh

# Set this to the name of your key, or your user name.
PEMUSER=robm@ncsa.uiuc.edu
# Set these to the location of your public and secret key files
PUBKEY=$HOME/.key-public
SECKEY=$HOME/.key-secret
# Set this to the password to your secret key
KEYPASS=mypassword
# Set this to your system's uuencode, or to my included version if your
# system doesn't have one (AIX)
UUENCODE=/bin/uuencode
# Set this to the location of your RIPEM executable
RIPEMBIN=/usr/local/bin/ripem

$UUENCODE foo | $RIPEMBIN -e -h i -Y g -u $PEMUSER -s $SECKEY -p $PUBKEY -k $KEYPASS -r $*




